version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: main
    volumes:
      - postgres-db-volume:/var/lib/postgresql-candidates/data
    ports:
      - 5432:5432

volumes:
  postgres-db-volume:
